### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by joemasilotti** [Tonksthebear/classy-yaml#2]
`$ ./bin/test` produces

```
/Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rails/plugin/test (LoadError)
```

`$ rake` produces

```
/Users/joemasilotti/workspace/forks/classy-yaml/test/dummy/config/application.rb:7:in `<top (required)>': uninitialized constant Bundler (NameError)
```

**Comment by Tonksthebear** [comment]
I haven't set up any tests yet. I just followed rails documentation on how to get a new engine up and running and published. I'll follow steps to get that going now though

**Comment by Tonksthebear** [comment]
Ok I just set up some basic tests. Coverage still needs to be better, but it is at least a start!

**Comment by joemasilotti** [comment]
Love it!
