### ISSUE TITLE
Require minimum amount of gems possible

### ISSUE THREAD

**Issue by natematykiewicz** [Tonksthebear/classy-yaml#3]
Hey there! Congrats on your first gem! I stumbled across this gem on Twitter and thought I’d provide you a little feedback.

Having `rails` as a dependency is not great for a gem. Generally, it’s suggested to only include the specific parts of Rails that you actually use.

Just skimming your codebase, it seems like you only need activesupport, actionpack, and railties.

By adding rails as a whole as a dependency, you’re requiring apps to include ActiveRecord, ActionMailer, ActionMailbox, ActiveJob, ActionCable, etc as a dependency. This isn’t ideal because some apps try to cut down on their dependencies by avoiding parts of Rails that they don’t use.

Here’s an example of a Basecamp gem that extends the rails query logs to include info about the current action. Instead of requiring rails, it requires actionpack and activerecord. https://github.com/basecamp/marginalia/blob/master/marginalia.gemspec

**Comment by Tonksthebear** [comment]
Hey @natematykiewicz, thank you for the feedback. I REALLY appreciate you writing this up. I had no idea, as the gems I looked at as an example just included `rails` like I did. Not only did you point this out, but you already found what I needed to include AND posted a great link, so thank you 👍 

I'll get an update out soon with the necessary changes. Thanks again!

**Comment by natematykiewicz** [comment]
Yeah, I'm not sure if you remember, but a few months back activestorage was unable to be installed for about a day. ActiveStorage depended on a gem called mimemagic and mimemagic had a licensing problem and had to yank a bunch of versions. ActiveStorage ended up removing mimemagic as a dependency, adding more logic to Rails' `marcel` gem. https://github.com/rails/rails/issues/41750

A lot of apps that don't use activestorage ended up just removing `gem 'rails'` from their Gemfile, and replacing it with a bunch of lines for the parts of Rails they actually use (avoiding ActiveStorage). But then some people who did this ran into problems because other gems they used required "rails" instead of just the parts of Rails they needed. A lot of people (including myself) learned a lot that day. So I figured I'd pass on the knowledge.

https://github.com/rails/rails/issues/41750

**Comment by Tonksthebear** [comment]
Ah yes, I remember that. I was just fortunate enough that the issues were resolved by the time I started looking into it. I heard about some of what you said on podcasts, but the headaches it cause are now clearer to me.

#4 should hopefully take care of this issue. If you want to look it over to make sure I did it properly, let me know. It's absolutely not your responsibility though, so no offense taken if you don't want to bother 👍 I'll close this issue when that's merged so I'll give it a day or so unless you say otherwise

**Comment by Tonksthebear** [comment]
Ok I went ahead and merged it. Thanks again for bringing this to my attention!
